# Generated by Django 6.1.1 on 2026-09-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, max_length=128, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_type', models.CharField(max_length=128)),
                ('profile_name', models.CharField(blank=True, max_length=128, null=True)),
                ('user_login', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=128)),
                ('device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.networkdevices')),
            ],
        ),
    ]
