# Generated by Django 6.1.1 on 2026-09-23 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='Имя хоста')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP адрес управления')),
                ('platform', models.CharField(choices=[('cisco_iosxe', 'Cisco IOS-XE'), ('cisco_nxos', 'Cisco NX-OS'), ('arista_eos', 'Arista EOS'), ('juniper_junos', 'Juniper JunOS'), ('huawei_vrp', 'Huawei VRP')], default='cisco_iosxe', max_length=30)),
                ('login', models.CharField(max_length=50, verbose_name='Имя пользоавтеля')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название профиля')),
                ('description', models.TextField(blank=True, verbose_name='Описание сценария')),
            ],
        ),
        migrations.RemoveField(
            model_name='ports',
            name='device_ip',
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя интерфейса (e.g. TenGigE0/0/1)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание интерфейса')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='homepage.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успешно завершено'), ('failed', 'Завершено с ошибками')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log_output', models.JSONField(blank=True, default=dict, verbose_name='Лог Nornir по хостам')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('shutdown', 'Отключить (Shutdown)'), ('no_shutdown', 'Включить (No Shutdown)'), ('apply_acl', 'Применить защитный ACL')], default='shutdown', max_length=32)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.interface')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homepage.profile')),
            ],
            options={
                'unique_together': {('profile', 'interface')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='interfaces',
            field=models.ManyToManyField(related_name='profiles', through='homepage.ProfileItem', to='homepage.interface'),
        ),
        migrations.DeleteModel(
            name='NetworkDevices',
        ),
        migrations.DeleteModel(
            name='Ports',
        ),
    ]
